### ISSUE TITLE
0.5.2 crashes with RandomPatches

### ISSUE THREAD

**Issue by Anthonity** [CleanroomMC/GroovyScript#78]
This doesn't happen with 0.4.6

**Comment by brachy84** [comment]
crash log pls

**Comment by Anthonity** [comment]
also happens with 0.6.1
[latest.log](https://github.com/CleanroomMC/GroovyScript/files/12440423/latest.log)

**Comment by WaitingIdly** [comment]
Because of how Random Patches applies its patch to the Minecraft Client, basically anything else that interacts with it will generate a crash - which GroovyScript does in its `GuiScreenMixin` to improve copying functionality, introduced in this commit https://github.com/CleanroomMC/GroovyScript/commit/f5c86a54263277ce0d995766df728520ae10b886.

This can be prevented by changing the Random Patches config setting to `B:patchMinecraftClass=false`. 

Note that if you look in the reported diff, between [`v0.4.6` and `v0.5.2`](https://github.com/CleanroomMC/GroovyScript/compare/v0.4.6...v0.5.2), you wont find this commit, as it was introduced prior to `v0.4.6` - specifically `v0.4.0`. This is reflected in actual testing, as it is not experienced in `v0.3.1` and experienced in `v0.4.0`

Additionally, while Universal Tweaks doesn't fully replicate the features of Random Patches, it contains most of them, so i would suggest trying to switch to that instead.
