### ISSUE TITLE
issue with midnight fishing table

### ISSUE THREAD

**Issue by Biviho** [CleanroomMC/GroovyScript#91]
the game chrash on loading a world with groovyscript and Midnight dimension, there are no scripts in groovy, tested in a bug modpack (400+) and in a light modpack for texting purposes to be sure, and it crash with midnight and groovy together

groovy script version: 0.6.4
[the log](https://logpaste.com/XAa9l3LS)

the crash is from the midnight side, but they are not supporting 1.12 anymore, is there something you can do?

**Comment by Nrmot** [comment]
> The crash is from the Midnight side. 

Unfortunately there is no way to fix it from Groovyscript side. 
 
Since the error `com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: midnight_fishing` is shown, you could try removing all scripts from the mod pack. However if it is still the case, it cannot be fixed on groovyscript side as this crash report seems to be other mod issue.

**Comment by Biviho** [comment]
i see, thank you for lloking into it, talking on discord i figured out i can remove the fishing table from midnight from loading by interrupting the event, i'll look if there is a way to add it back in a different way or just change how the fishing in the dimension work with some mods

**Comment by brachy84** [comment]
Fixed in #95
